### ISSUE TITLE
License

### ISSUE THREAD

**Issue by johanneswilm** [dharshakch97/sort-visualizer#1]
Hey,
it looks like you forgot to specify a license. Which open source license is this available under?

**Comment by dharshakrv** [comment]
Hey, I didn't know about the licence. Can you help me to specify a license for this repository?

**Comment by johanneswilm** [comment]
Hey, sure. The easiest is to pick one of the open source licenses using for example this click-through guide: https://choosealicense.com/

Once you have chosen one, I'll be happy to add the appropriate text to your github repository unless you can do that yourself.

**Comment by dharshakch97** [comment]
Yup! I added the MIT license
